image: devago/docker-compose
services:
  - docker:dind

cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
  paths:
    - node_modules

stages:
  - build
  - deploy

variables:
  PROJECT: paytech
  STAGE_HOST: paytech-com-ua.avgr.it
  COMPOSE_PROJECT_NAME: react-app-${PROJECT}-${CI_COMMIT_REF_SLUG}
  VIRTUAL_HOST: react-app-${PROJECT}-${CI_COMMIT_REF_SLUG}.${STAGE_HOST}

  DOCKER_MACHINE_STAGE: stage1

  DOCKER_DRIVER: overlay2
  DOCKER_CONFIG: ".docker-config/"

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

include:
  - local: /.gitlab/ci/build.stage.gitlab-ci.yml
  - local: /.gitlab/ci/deploy.stage.gitlab-ci.yml
  - local: /.gitlab/ci/destroy.stage.gitlab-ci.yml
