deploy_stage:
  tags:
    - docker
  stage: deploy
  variables:
    COMPOSE_FILE: $COMPOSE_FILE_STAGE
  script:
    - echo $CI_JOB_STAGE
    - eval "$(docker-machine env ${DOCKER_MACHINE_STAGE})"
    - ./build.sh deploy_stage
    - echo https://$VIRTUAL_HOST
  environment:
    name: ${CI_COMMIT_REF_NAME}
    url: https://${VIRTUAL_HOST}
    on_stop: destroy
    auto_stop_in: 1 week
  only:
    - branches
